(function () {
  // Dependency-free client-side filter for the samples.honua.io gallery
  // index. Progressive enhancement: with this script absent, every card is
  // visible and the page is still fully readable/linkable.
  //
  // ?caps=key1,key2 deep-link contract mirrors honua.io/capabilities.html's
  // assets/capability-filter.js (honua-io/honua-site) so a link generated by
  // that page's capability picker, or by honua-esri-assess's migration
  // scanner, lands here pre-filtered to the matching sample cards. Semantics:
  // OR within the capability facet (a card matching ANY listed key is
  // shown), AND across facets (capability / SDK / edition / source repo).
  //
  // Copied verbatim into site/assets/gallery-filter.js by
  // scripts/build-gallery.mjs.

  function safe(fn) {
    try {
      return fn();
    } catch {
      return undefined;
    }
  }

  function cards() {
    return Array.prototype.slice.call(document.querySelectorAll(".card[data-id]"));
  }

  function checkboxesIn(selector) {
    return Array.prototype.slice.call(document.querySelectorAll(selector));
  }

  function selectedValues(selector) {
    return checkboxesIn(selector)
      .filter(function (box) {
        return box.checked;
      })
      .map(function (box) {
        return box.value;
      });
  }

  function csv(value) {
    return (value || "")
      .split(",")
      .map(function (v) {
        return v.trim();
      })
      .filter(Boolean);
  }

  function intersects(a, b) {
    for (var i = 0; i < a.length; i++) {
      if (b.indexOf(a[i]) !== -1) return true;
    }
    return false;
  }

  function currentShareUrl(capKeys) {
    var url = new URL(window.location.href);
    url.search = "";
    if (capKeys.length) url.searchParams.set("caps", capKeys.join(","));
    return url.toString();
  }

  function applyFilters() {
    var capKeys = selectedValues(".filter-cap");
    var sdks = selectedValues(".filter-sdk");
    var editions = selectedValues(".filter-edition");
    var sources = selectedValues(".filter-source");

    var visibleCount = 0;
    var total = 0;

    document.querySelectorAll(".category").forEach(function (section) {
      var visibleInSection = 0;
      Array.prototype.slice.call(section.querySelectorAll(".card[data-id]")).forEach(function (card) {
        total++;
        var cardCaps = csv(card.getAttribute("data-capabilities"));
        var cardSdks = csv(card.getAttribute("data-sdks"));
        var cardEdition = card.getAttribute("data-edition") || "";
        var cardSource = card.getAttribute("data-source") || "";

        var show =
          (!capKeys.length || intersects(capKeys, cardCaps)) &&
          (!sdks.length || intersects(sdks, cardSdks)) &&
          (!editions.length || editions.indexOf(cardEdition) !== -1) &&
          (!sources.length || sources.indexOf(cardSource) !== -1);

        card.hidden = !show;
        if (show) {
          visibleInSection++;
          visibleCount++;
        }
      });
      section.hidden = visibleInSection === 0;
    });

    var status = document.getElementById("filter-status");
    if (status) {
      var anyFilter = capKeys.length || sdks.length || editions.length || sources.length;
      status.textContent = anyFilter
        ? "Showing " + visibleCount + " of " + total + " sample(s)."
        : "Showing all " + total + " sample(s).";
    }

    var emptyState = document.getElementById("empty-state");
    if (emptyState) emptyState.hidden = visibleCount !== 0;

    var shareInput = document.getElementById("cap-share-url");
    if (shareInput) shareInput.value = currentShareUrl(capKeys);
    var shareRow = document.getElementById("cap-share-row");
    if (shareRow) shareRow.hidden = capKeys.length === 0;
  }

  function readCapsParam() {
    var params = new URLSearchParams(window.location.search);
    var raw = params.get("caps");
    return raw ? csv(raw) : [];
  }

  function bindCopyButton() {
    var button = document.getElementById("cap-share-copy");
    var status = document.getElementById("cap-share-status");
    if (!button) return;
    button.addEventListener("click", function () {
      var input = document.getElementById("cap-share-url");
      if (!input || !input.value) return;
      var done = function (ok) {
        if (status) status.textContent = ok ? "Copied!" : "Select and copy the link above.";
      };
      if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard
          .writeText(input.value)
          .then(function () {
            done(true);
          })
          .catch(function () {
            input.select();
            done(false);
          });
      } else {
        input.select();
        safe(function () {
          document.execCommand("copy");
        });
        done(true);
      }
    });
  }

  function bindClearButton() {
    var button = document.getElementById("filter-clear");
    if (!button) return;
    button.addEventListener("click", function () {
      checkboxesIn(".filter-cap, .filter-sdk, .filter-edition, .filter-source").forEach(function (box) {
        box.checked = false;
      });
      safe(applyFilters);
    });
  }

  function init() {
    var presetCaps = safe(readCapsParam) || [];
    if (presetCaps.length) {
      checkboxesIn(".filter-cap").forEach(function (box) {
        if (presetCaps.indexOf(box.value) !== -1) box.checked = true;
      });
    }

    checkboxesIn(".filter-cap, .filter-sdk, .filter-edition, .filter-source").forEach(function (box) {
      box.addEventListener("change", function () {
        safe(applyFilters);
      });
    });

    bindClearButton();
    bindCopyButton();
    safe(applyFilters);
  }

  document.addEventListener("DOMContentLoaded", init);
})();
